### ISSUE TITLE
Cohort visualization is duplicating months and showing too many months.

### ISSUE THREAD

**Issue by jasonshah** [getredash/redash#1201]
### Issue Summary

A table whose dates are first days of the month for the past six months is rendering the cohort visualization with an extra month, and with some months duplicated.

### Steps to Reproduce

Create a cohort visualization based on the attached data (Visualization type: cohort; Time Interval: monthly). Notice that the month column in the data shows January through July.
The resulting visualization shows as the attached. Notice 
1.) the presence of December, which does not exist in the table, and 
2.) the duplicate March and May months.
![Cohorot visualization](https://cloud.githubusercontent.com/assets/24223/17039994/e786bd4e-4f62-11e6-8c11-e6cb87124b9d.png)

### Technical details:

* Redash Version: 0.10.1+b1836
* Browser/OS: Chrome on Mac OS X 10.10.5
* How did you install Redash: Docker

[Data.csv.zip](https://github.com/getredash/redash/files/377058/Data.csv.zip)

**Comment by jasonshah** [comment]
Confirmed that this is an issue in 0.11.0+b2016 as well.

**Comment by jasonshah** [comment]
This appears to be a timezone issue.
I am in CST. When I look at "2016-01-01 00:00:00" as it reaches the section of cornelius.js code that renders the labels, it believes the date to be "Thu Dec 31 2015 18:00:00 GMT-0600". This then gets changed to "December 2015" in the cohort table above.
Any suggestions on how to fix?

**Comment by arikfr** [comment]
@jasonshah thanks for the detailed report. Can you link to the line in [cornelius.js](https://github.com/restorando/cornelius/blob/master/src/cornelius.js) it gets changed at?

One possible fix is to pass datetime objects with timezone set to Cornelius, so it won't change it. But I prefer to avoid that, because we're trying to stay away from making assumptions on your data.

**Comment by mtrbean** [comment]
I'm also running into the same problem. I believe https://github.com/restorando/cornelius/blob/master/src/cornelius.js#L160 is how Cornelius renders the timestamp.

**Comment by edowdy** [comment]
We just ran into the same issue. Has this has been solved yet?

**Comment by JeongsangBaek** [comment]
Cornelius.js render date by adding +1 date period(day, week, month). It makes some problems. Descending date is also not working. It has to be modified to read date value returned by query.

**Comment by JeongsangBaek** [comment]
I'm worried that I think Cornelius.js is out of management.

**Comment by rdtr** [comment]
I also hit by this issue today.

I use daily Cohort visualization and dates shown in a cohort are all one day behind compared to ones that a table (= actual query result) shows.

As @jasonshah I can hardcode some offset in my query, but our dashboard can be seen by multiple timezones, so it's problematic.

**Comment by susodapop** [comment]
Bumping this issue: it's still present in SaaS version `c7e0990`.

**Comment by kravets-levko** [comment]
@susodapop  tried to reproduce this issue on `master` using data provided by @jasonshah and seems that visualizations works fine:

![image](https://user-images.githubusercontent.com/12139186/84039762-69a24c80-a9aa-11ea-8644-43b94f24e1ba.png)

Can you please try to reproduce this bug on https://redash-preview.netlify.app/ to either confirm that it's fixed or create a demo with the bug to help me investigate it? Thank you!
