### ISSUE TITLE
Migrations in new permissions system

### ISSUE THREAD

**Issue by TonyStarkBy** [getredash/redash#733]
There is one small bug in: https://github.com/getredash/redash/commit/f7b57fa580a6556f8f101856aecc940283a024ca

Migrations list:
0018_add_groups_refs.py
0019_add_super_admin_permission.py
0020_add_group_type.py

```
Applying 0018_add_groups_refs.py...
[52.31.96.150] run: sudo sudo -u redash PYTHONPATH=. bin/run python migrations/0018_add_groups_refs.py
[52.31.96.150] out: [2016-01-05 11:29:52,384][PID:17111][WARNING][redash.query_runner] MQL query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[52.31.96.150] out: [2016-01-05 11:29:52,435][PID:17111][WARNING][redash.query_runner] Oracle query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[52.31.96.150] out: [2016-01-05 11:29:52,549][PID:17111][ERROR][peewee] SELECT "t1"."id", "t1"."org_id", "t1"."type", "t1"."name", "t1"."permissions", "t1"."created_at" FROM "groups" AS t1 WHERE ("t1"."name" = %s) LIMIT 1 [u'default']
[52.31.96.150] out: Traceback (most recent call last):
[52.31.96.150] out:   File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 360, in execute_sql
[52.31.96.150] out:     cursor.execute(sql, params or ())
[52.31.96.150] out: ProgrammingError: column t1.type does not exist
[52.31.96.150] out: LINE 1: SELECT "t1"."id", "t1"."org_id", "t1"."type", "t1"."name", "...
[52.31.96.150] out:                                          ^
[52.31.96.150] out:
[52.31.96.150] out: Traceback (most recent call last):
```

We need to run 0020_add_group_type.py first, and then 0018_add_groups_refs.py

Good luck =)

**Comment by arikfr** [comment]
Nice catch. I'll fix that.

**Comment by MaxPleaner** [comment]
Just wondering if the fabfile.py gist has been updated? I just got this error.

**Comment by arikfr** [comment]
@MaxPleaner maybe it will be more efficient if we continue over chat. Join our Slack: http://slack.redash.io and ping me there.

But for your question -- the migrations were fixed in #735, so you shouldn't be getting any errors. Do you have an output of the first time it failed? What was the exact error?

**Comment by shishirsharma** [comment]
main failed on upgrading a fresh installation 

Applying 0014_migrate_existing_es_to_kibana.py...
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] run: sudo sudo -u redash PYTHONPATH=. bin/run python migrations/0014_migrate_existing_es_to_kibana.py
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out: [2016-01-20 13:06:36,651][PID:6371][WARNING][redash.query_runner] MQL query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out: [2016-01-20 13:06:36,700][PID:6371][WARNING][redash.query_runner] Oracle query runner enabled but not supported, not registering. Either disable or install missing dependencies.
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out: [2016-01-20 13:06:36,740][PID:6371][ERROR][peewee] SELECT "t1"."id", "t1"."org_id", "t1"."name", "t1"."type", "t1"."options", "t1"."queue_name", "t1"."scheduled_queue_name", "t1"."created_at" FROM "data_sources" AS t1 []
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out: Traceback (most recent call last):
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:   File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 360, in execute_sql
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:     cursor.execute(sql, params or ())
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out: ProgrammingError: column t1.org_id does not exist
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out: LINE 1: SELECT "t1"."id", "t1"."org_id", "t1"."name", "t1"."type", "...
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:                           ^
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out: 
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out: Traceback (most recent call last):
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:   File "migrations/0014_migrate_existing_es_to_kibana.py", line 7, in <module>
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:     for ds in DataSource.select():
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2689, in __iter__
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:     return iter(self.execute())
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2682, in execute
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:     self._qr = ResultWrapper(model_class, self._execute(), query_meta)
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:   File "/opt/redash/redash.0.9.1.b1377/redash/metrics/database.py", line 50, in metered_execute
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:     result = real_execute(self, *args, **kwargs)
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2371, in _execute
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:     return self.database.execute_sql(sql, params, self.require_commit)
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:   File "/opt/redash/redash.0.9.1.b1377/redash/metrics/database.py", line 22, in execute_sql
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:     result = super(MeteredPostgresqlExtDatabase, self).execute_sql(*args, **kwargs)
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:   File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 369, in execute_sql
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:     self.commit()
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:   File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2922, in __exit__
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:     reraise(new_type, new_type(*exc_value.args), traceback)
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:   File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 360, in execute_sql
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:     cursor.execute(sql, params or ())
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out: peewee.ProgrammingError: column t1.org_id does not exist
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out: LINE 1: SELECT "t1"."id", "t1"."org_id", "t1"."name", "t1"."type", "...
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:                           ^
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out: 
[ec2-54-169-153-75.ap-southeast-1.compute.amazonaws.com] out:

**Comment by arikfr** [comment]
@MaxPleaner @shishirsharma looks like if you upgrade from an older version than migrations still fail (I only tested with 0.8.0+).

What you can do is run migrations 17 & 18 first, and then the rest. 

If you tell me what version you had before, I will try to reproduce this and fix the migrations.

**Comment by shishirsharma** [comment]
I checked and in latest versin 0020_add_group_type.py migration is no longer there. instead new list is like this 

```
-rw-rw-r-- 1 ubuntu ubuntu  214 Jan 20 20:20 0014_migrate_existing_es_to_kibana.py
-rw-rw-r-- 1 ubuntu ubuntu  201 Jan 20 20:20 0015_add_schedule_query_permission.py
-rw-rw-r-- 1 ubuntu ubuntu  350 Jan 20 20:20 0016_add_alert_subscriber.py
-rw-rw-r-- 1 ubuntu ubuntu  327 Jan 20 20:20 0016_drop_tables_from_group.py
-rw-rw-r-- 1 ubuntu ubuntu 1266 Jan 20 20:20 0017_add_organization.py
-rw-rw-r-- 1 ubuntu ubuntu 1582 Jan 20 20:20 0018_add_groups_refs.py
-rw-rw-r-- 1 ubuntu ubuntu  190 Jan 20 20:20 0019_add_super_admin_permission.py
-rw-rw-r-- 1 ubuntu ubuntu  676 Jan 20 20:20 0020_change_ds_name_to_non_uniqe.py

```

this still fails as there is no type in group table

**Comment by yanenok** [comment]
I have the same issue when trying to update both redash-demo vagrant box (v. 0.4.0+b589) and redash instance installed on ubuntu vm via provisioning script (0.7.1+b1015).

**Comment by stanhu** [comment]
@arikfr I upgraded from 0.8.2.b1118 to 0.9.1.b1377, and I ended up applying migrations 17 and 18 by hand and then applying the rest. The problem looks like the models expect to have the fields when the `SELECT` occurs. I think it makes sense to rename 17 and 18 before 14.

**Comment by arikfr** [comment]
I've updated all migrations to work with new code (7a7e5be). I ran them all on a new Vagrant box, so I hope that I managed to cover all cases this time. But it's possible that some migrations will still fail due to different data than I used. If it happens, just post your stacktrace here.

Thanks and sorry for all who had trouble with this.

(note that this it not yet in master. it will soon be)

**Comment by myungK** [comment]
i also have same isue in re:dash 0.10.1
i use that ami : eu-west-1: ami-f3910780 which Re:dash Doc is guided
i don't have no idea to solve the this issue
and i also check the new code (7a7e5be) which changed.
plz help me
=================================
File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2922, in __exit__
    reraise(new_type, new_type(*exc_value.args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 360, in execute_sql
    cursor.execute(sql, params or ())
ProgrammingError: column t1.org_id does not exist
LINE 1: ... "t1"."id", "t1"."updated_at", "t1"."created_at", "t1"."org_...

**Comment by jacobus** [comment]
Good day,
I tried upgrading from 9.1 to 1.0 on Ubuntu 14.04. I'm getting the following error:

  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 438, in __protected_call__
    return self.run(*args, **kwargs)
  File "/opt/redash/redash.0.12.0.b2449/redash/tasks/queries.py", line 259, in refresh_queries
    for query in models.Query.outdated_queries():
  File "/opt/redash/redash.0.12.0.b2449/redash/models.py", line 793, in outdated_queries
    for query in queries:
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2689, in __iter__
    return iter(self.execute())
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2682, in execute
    self._qr = ResultWrapper(model_class, self._execute(), query_meta)
  File "/opt/redash/redash.0.12.0.b2449/redash/metrics/database.py", line 50, in metered_execute
    result = real_execute(self, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2371, in _execute
    return self.database.execute_sql(sql, params, self.require_commit)
  File "/opt/redash/redash.0.12.0.b2449/redash/metrics/database.py", line 22, in execute_sql
    result = super(MeteredPostgresqlExtDatabase, self).execute_sql(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 369, in execute_sql
    self.commit()
  File "/usr/local/lib/python2.7/dist-packages/peewee.py", line 2922, in __exit__
    reraise(new_type, new_type(*exc_value.args), traceback)
  File "/usr/local/lib/python2.7/dist-packages/playhouse/postgres_ext.py", line 360, in execute_sql
    cursor.execute(sql, params or ())
ProgrammingError: column t1.version does not exist
LINE 1: ... "t1"."id", "t1"."updated_at", "t1"."created_at", "t1"."vers...
                                                             ^
Please help. I see some comments above refer to supplying migrations. How do I do that?

Kind regards,
Jack

**Comment by arikfr** [comment]
@jacobus It looks like some migrations were not applied.

**Comment by jacobus** [comment]
Hi, thanks for getting back to me. How can I re-apply the migrations or
re-install re-dash?
